### ISSUE TITLE
ResultListField improvement

### ISSUE THREAD

**Issue by furkanyilmazx** [muendiz/rest-art#15]
I want type code like following

![image](https://user-images.githubusercontent.com/7690380/43706701-c88d9ab8-996e-11e8-9dac-834b13f4feb2.png)

![image](https://user-images.githubusercontent.com/7690380/43706780-f7c2850a-996e-11e8-8717-a2ae3f4adc63.png)

**Comment by enginustun** [comment]
commit 0027894e6591399197db926a96ae2c02d0c90f0b closes this issue.
