### ISSUE TITLE
Add xhr.responseType check

### ISSUE THREAD

**Issue by barhantas** [muendiz/rest-art#27]
![image](https://user-images.githubusercontent.com/13484299/49714102-b3e32a00-fc5c-11e8-8b35-719b79df1afb.png)
![image](https://user-images.githubusercontent.com/13484299/49714123-c8272700-fc5c-11e8-8b3c-227613af4728.png)

**Comment by enginustun** [comment]
4dbb76c842d1b644caae9276a6be85ea29703389 fixed this issue.
