### ISSUE TITLE
Get resultListField from model config

### ISSUE THREAD

**Issue by enginustun** [muendiz/rest-art#7]
Currently, we are able to specify 'resultListField' in parameter while calling function.
`DerivedModelClass.all({ resultList:[], resultListField: 'content' })`;

If we update code as below:
![image](https://user-images.githubusercontent.com/5319936/41978082-aefa78c8-7a29-11e8-9bb0-887b15b19652.png)

We will be able to define resultListField in model class.
![image](https://user-images.githubusercontent.com/5319936/41978417-7f6b7156-7a2a-11e8-8091-52612a9b5810.png)

**Comment by furkanyilmazx** [comment]
I tried it today and it worked succeed. I had written like that "Device.setConfig('resultListField', 'content')" before your commit.

**Comment by furkanyilmazx** [comment]
great job :+1:
